version: "3.0"
services:
  web:
    build: 
      ports:
        - "3000:3000"
      networks:
        - compose-networks

  mysql:
    image: "mysql"
    ports:
      - "3500:3500"
    volumes:
      - .:/data/db
    networks:
      - compose-networks

networks:
  compose-networks:
